modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"

[[mods]]
modId="lasertag"
version="1"
displayName="Lasertag"
credits="Made in MCreator with <3"
displayURL="https://mcreator.net"
authors="StikyPiston2483"

[[dependencies.lasertag]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




